### ISSUE TITLE
Feature Request: Zoom In time into hours

### ISSUE THREAD

**Issue by alpercetiner84** [bardsoftware/ganttproject#1762] opened 2020-08-16 12:47 UTC
Hello dear GanttProject Team,

I would like to use the software for documentation of activities in major incidents, where multiple teams are involved in fixing a grievous bug. 

I believe that having those activities visualized is a powerful tool to analyze our reaction times, synergies, dependencies.

This will help to have a better report and reflection on a major incident report so we can improve measures taken by various groups involved in an incident.

There is some manual Excel work (see screenshot) that I have done in time restriction and we already can see the benefits. Having this in a professional tool will elevate our processes.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/43346588/90334630-5bd2fe00-dfcf-11ea-9401-b8db8ef1dbed.png)

Thanks in advance and best regards,

**Comment by dbarashev** [comment] 2020-08-16 18:32
I don't understand what is requested in this issue. If the request is to support hour-level granularity then it is a duplicate of #225

**Closed by dbarashev** 2020-08-16 18:32 UTC
