### ISSUE TITLE
indenting sub-project groups works not for all sup-project groups

### ISSUE THREAD

**Issue by xs133** [bardsoftware/ganttproject#1169] opened 2015-09-04 09:55 UTC
I  want to indent a project group into a the group above 
![Uploading accepted indenting.jpg…]() and it would work. If I try the same on the next grope it will not allow me to indent into the grou above. 
![Uploading denied indending.jpg…]()
ubfortunate I do not get a hint of the case of the issue.

**Comment by dbarashev** [comment] 2015-09-04 10:47
Anything went wrong with the images upload?

**Comment by xs133** [comment] 2015-09-04 14:24
I attached the two files – same name

 

Von: Dmitry Barashev [mailto:notifications@github.com] 
Gesendet: Freitag, 4. September 2015 12:48
An: bardsoftware/ganttproject
Cc: xs133
Betreff: Re: [ganttproject] indenting sub-project groups works not for all sup-project groups (#1169)

 

Anything went wrong with the images upload?

**Comment by dbarashev** [comment] 2015-09-04 14:26
I don't see any images here. I suspect that GitHub doesn't support email attachments. Please attach the images in the web UI.

**Comment by xs133** [comment] 2015-09-04 14:57
The two files no reattached.
![Uploading denied indending.jpg…]()
![Uploading accepted indenting.jpg…]()

**Comment by xs133** [comment] 2015-09-04 15:03
I still do not see the files in the preview, these are small jpg's. Drag and drop or seleting the files makes no differents.
![denied indending](https://cloud.githubusercontent.com/assets/13802775/9686925/b44aa97e-5326-11e5-9afd-ee62d7e6e62f.jpg)
![accepted indenting](https://cloud.githubusercontent.com/assets/13802775/9686926/b451432e-5326-11e5-9c69-c2f081ab6d7b.jpg)

**Comment by dbarashev** [comment] 2015-09-04 15:06
Can you attach or send the project file itself? And did you really mean to close this issue?

**Comment by xs133** [comment] 2015-09-04 15:18
>Github is not allowing to attach *.gan

 

Von: Dmitry Barashev [mailto:notifications@github.com] 
Gesendet: Freitag, 4. September 2015 17:07
An: bardsoftware/ganttproject
Cc: xs133
Betreff: Re: [ganttproject] indenting sub-project groups works not for all sup-project groups (#1169)

 

Can you attach or send the project file itself? And did you really mean to close this issue?

**Comment by xs133** [comment] 2015-09-04 15:19
Tehe test project file i
is attached.

**Comment by dbarashev** [comment] 2015-09-04 15:27
I don't see any .gan file here. 
You can find our contact email on http://ganttproject.biz/about

**Comment by xs133** [comment] 2015-09-04 15:37
Dragging the denied project group was possible. It looks like, that one dependency between a task and a group was causing a circular dependency. "Drag and drop" action deleted the dependency without any information.

**Comment by dbarashev** [comment] 2015-09-04 15:41
Yes, circular dependencies is one of the likely reasons. I can't say anything certain until I see the file, though. Unless you believe that the issue is resolved now, please send the file by email. You can find our contact email on http://ganttproject.biz/about

**Comment by dbarashev** [comment] 2015-09-07 11:47
For the record: the issue was the dependency between tasks, and it is expected that indent is not possible in this case. However, drag'n'drop violates the rule and removes the dependency. I submitted issue #1170 for that.

**Closed by dbarashev** 2015-09-07 11:47 UTC
