### ISSUE TITLE
Can't open dialogs from dropdown menus

### ISSUE THREAD

**Issue by cornercase** [bardsoftware/ganttproject#1490] opened 2018-02-09 22:29 UTC
If I try to open commands from dropdowns that should produce another window, nothing happens.  For example, clicking Project -> Properties or Web Server -> Open from server does not cause anything to happen.

OS: MacOS High Sierra 10.13.1
GanttProject: 2.8.6 Pilsen (build 2231)

Log file snippet:
> INFO: Deleting old auto-save files

> Creating main frame...
> 1. loading look'n'feels
> no editor for column=0 class=interface javax.swing.Icon
> no editor for column=1 class=interface javax.swing.Icon
> no editor for column=2 class=interface javax.swing.Icon
> 2. loading options
> 3. creating menus...
> 4. creating views...
> 5. calculating size and packing...
> 6. changing language ...
> 7. first attempt to restore bounds
> Feb 09, 2018 3:32:29 PM net.sourceforge.ganttproject.GPLogger log
> INFO: Bounds stored in the  options: java.awt.Rectangle[x=0,y=143,width=1680,height=765]
> 8. finalizing...
> Main frame created
> Feb 09, 2018 3:32:29 PM net.sourceforge.ganttproject.GPLogger log
> INFO: Bounds after setVisible: java.awt.Rectangle[x=0,y=143,width=1680,height=765]
> Splash closed
> Resizing window...
> Feb 09, 2018 3:32:29 PM net.sourceforge.ganttproject.GPLogger log
> INFO: Bounds after opening: java.awt.Rectangle[x=0,y=143,width=1680,height=765]
> Feb 09, 2018 3:32:29 PM net.sourceforge.ganttproject.GPLogger log
> INFO: Bounds stored in the  options: java.awt.Rectangle[x=0,y=143,width=1680,height=765]
> Feb 09, 2018 3:32:34 PM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
> INFO: Scanning font directories...
> Feb 09, 2018 3:32:34 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
> INFO: scanning directory=/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/fonts
> Feb 09, 2018 3:32:35 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
> INFO: scanning directory=C:/windows/fonts
> Feb 09, 2018 3:32:35 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
> INFO: directory C:/windows/fonts is not readable
> Feb 09, 2018 3:32:35 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
> INFO: scanning directory=/usr/share/fonts/truetype
> Feb 09, 2018 3:32:35 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
> INFO: directory /usr/share/fonts/truetype is not readable
> Feb 09, 2018 3:32:35 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
> INFO: scanning directory=/System/Library/Fonts
> Feb 09, 2018 3:32:37 PM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
> INFO: scanning directory=/Applications/GanttProject.app/Contents/Java/plugins-2.8.6/org.ganttproject.impex.htmlpdf/resource/fonts
> Feb 09, 2018 3:32:37 PM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
> INFO: Scanning font directories completed
> Feb 09, 2018 4:15:43 PM net.sourceforge.ganttproject.GPLogger log
> INFO: [GanttOptions] save(): finished!!
> no editor for column=0 class=interface javax.swing.Icon
> no editor for column=1 class=interface javax.swing.Icon
> no editor for column=2 class=interface javax.swing.Icon
> Feb 09, 2018 4:15:48 PM net.sourceforge.ganttproject.GPLogger log
> INFO: Main window has closed
> Feb 09, 2018 4:15:48 PM net.sourceforge.ganttproject.GPLogger log
> INFO: Program terminated
> Feb 09, 2018 4:15:48 PM net.sourceforge.ganttproject.GPLogger log
> INFO: [GanttOptions] save(): finished!!

**Comment by dbarashev** [comment] 2018-02-09 23:10
Wow. Thanks for reporting. This seems to be reproducible on Mac OSX only with the native look and feel and not for all dialogs (e.g. task properties dialog works fine). We'll surely fix it as soon as possible, but meanwhile you can use a workaround: 
* open file `.ganttproject` which is sitting in your home folder (which usually `/Users/<your user name>` on Mac OSX) in any text editor. Notice the dot in the file name -- it may not be shown in Finder interface. Typing this line in Terminal should do the trick: `open ~/.ganttproject` and open the file in a text editor
* find lines with `<option ...>` tags
* insert this one anywhere between other options:
```
   <option id="ui.laf" value="Plastic"/>
```

**Comment by dbarashev** [comment] 2018-02-10 02:03
Linking #1487  which is most likely caused this issue.

**Comment by dbarashev** [comment] 2018-02-11 00:35
Hi, disk image with the new build (ganttproject-2.8.6-r2233.dmg) is available on the release page on GitHub: https://github.com/bardsoftware/ganttproject/releases/tag/ganttproject-2.8.6

Can you please check if the issue is fixed now?

**Comment by aldovitch** [comment] 2018-02-11 19:28
It's OK with this new build.
Thank you.

**Comment by dbarashev** [comment] 2018-02-12 15:23
Cool, thanks for testing! The build is now available from the official website.

**Closed** 2018-02-12 15:24 UTC
Labels: Fix committed to the repository, OpSys-OSX, __Target-Pilsen, bug
