### ISSUE TITLE
can't delete a resource from a task!

### ISSUE THREAD

**Issue by srwhitman** [bardsoftware/ganttproject#1464] opened 2017-10-11 15:40 UTC
When I go into a task assign a resource and save the task and later delete that resource, it still shows up on the timeline and later when I go into the task itself its still there!

**Comment by dbarashev** [comment] 2017-10-11 16:10
When you say "delete that resource", do you mean that you really delete the resource itself, or that you remove resource from the resources assigned to the task?

**Comment by srwhitman** [comment] 2017-10-11 17:11
The latter - I tried to delete a resource from the task. I;'ve got version 2.8.5.  

    On Wednesday, October 11, 2017 9:11 AM, Dmitry Barashev <notifications@github.com> wrote:
 

 When you say "delete that resource", do you mean that you really delete the resource itself, or that you remove resource from the resources assigned to the task?—

**Comment by dbarashev** [comment] 2017-10-11 17:18
So, this seems to be a duplicate of #612 
Workaround: don't click dropdown with the resouce name if you need to delete resource assignment.

**Closed** 2017-10-22 16:17 UTC
