### ISSUE TITLE
Assign a color to a ressource

### ISSUE THREAD

**Issue by Asgatlat** [bardsoftware/ganttproject#1946] opened 2021-09-13 12:15 UTC
hi,
i would like to assign a color to a ressource
e.g : Team 1 in red / Team 2 in blue
i can't find where to set this, so i edit color for each task

thanks

**Comment by Asgatlat** [comment] 2021-09-30 09:04
![image](https://user-images.githubusercontent.com/86599367/135422037-dc3b4f97-202c-4e77-a6d2-90d824031213.png)
for exemple : in my screenshot, task in red is assign to team A / task in blue is for team B
i want in ressource setting to set a color for a Team, so when i assign a task to a team, the color is auto set
for now, i have to edit each task to change color

**Comment by dbarashev** [comment] 2021-09-30 10:08
So, seems to be a duplicate of #756

**Closed by dbarashev** 2021-09-30 10:08 UTC
Labels: duplicate
