### ISSUE TITLE
Task groups are not rescheduled when shifting project backwards

### ISSUE THREAD

**Issue by olassozeit** [bardsoftware/ganttproject#1224] opened 2016-03-10 09:22 UTC
When using the option to move the project start date (project settings – Calendar) in combination with rescheduling task groups are rescheduled correctly when the project start date is moved forward but incorrectly when it is moved backwards: A hard linked task group is not rescheduled (while single linked tasks are). Se pictures for demonstration.

This problem is disturbing but not critical as there is an easy work-around: If you want to move back and reschedule you have to move forward and reschedule first and then move back without rescheduling.

For solving this issue there is one special case to consider: If a task of the corresponding task group has a fixed begin date (additional constrain “earliest begin”) and is (through linking) always the first task of the group, the group start date cannot be moved to an earlier date as this fixed begin date. 
On the other hand the fixed begin date can lead to stretch the task group when other tasks not linked to the fixed date task are moved backwards.

Initial situation:
![gantt_01_initial_situation](https://cloud.githubusercontent.com/assets/12987894/13664830/a51ce978-e6a9-11e5-8c91-385d5dba7b2b.jpg)

Moved and rescheduled forward:
![gantt_02_moved_and_rescheduled](https://cloud.githubusercontent.com/assets/12987894/13664831/a51d88c4-e6a9-11e5-9569-f41f28cb55c7.jpg)

Moved and rescheduled backwards:
![gantt_03_moved_back_and_rescheduled](https://cloud.githubusercontent.com/assets/12987894/13664828/a5190574-e6a9-11e5-9ec0-64989aab736a.jpg)
![gantt_03b_moved_back_and_rescheduled_ commented](https://cloud.githubusercontent.com/assets/12987894/13664829/a51ccab0-e6a9-11e5-8596-1f0904d1c1ed.jpg)

**Comment by dbarashev** [comment] 2016-03-10 11:42
This is essentially a duplicate of #1173, just other way of reproducing

**Closed** 2021-04-26 15:08 UTC
