### ISSUE TITLE
Instability/Crashing on Mac

### ISSUE THREAD

**Issue by JenniferRP** [bardsoftware/ganttproject#2060] opened 2022-03-19 14:39 UTC
So, I decided to try this software again. Unfortunately, it is completely unstable on my system. It crashes out frequently, sometimes on launch (and by frequently I'm talking less than a minute).

Running MacOS Monterey 12.2.1, 2017 27" iMac. GanttProject is fully up-to-date at 3.2.3220. Here is the console summary, and I also attached the full report as a file.

Happy to assist with further troubleshooting.

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               GanttProject [7053]
Path:                  /Applications/GanttProject.app/Contents/MacOS/GanttProject
Identifier:            com.bardsoftware.ganttproject
Version:               3.2.3220 (3.2.3220)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-03-19 00:00:42.5198 -0400
OS Version:            macOS 12.2.1 (21D62)
Report Version:        12
Anonymous UUID:        616C7B78-AAD
[Gantt console report.txt](https://github.com/bardsoftware/ganttproject/files/8309442/Gantt.console.report.txt)
6-1E92-A52A-9E454498EC80

Time Awake Since Boot: 5300 seconds

System Integrity Protection: enabled

Crashed Thread:        28  Java: InvokeLaterDispatcher

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called

**Comment by dbarashev** [comment] 2022-03-19 15:01
Discussion on the support portal about the similar issue: https://help.ganttproject.biz/t/ganttproject-crashs-all-the-time-on-my-mac/4368/29

Chances are that the reasons are the same and the future solution (and [current workaround](https://help.ganttproject.biz/t/ganttproject-crashs-all-the-time-on-my-mac/4368/33)) are the same too.

**Comment by dbarashev** [comment] 2022-03-19 20:16
Can you please test this package? It is bundled with the latest Java 11 Runtime which hopefully fixes these issues.

https://storage.googleapis.com/dl.ganttproject.biz/ganttproject-3.2.3230/ganttproject-3.2.3230.dmg

**Comment by dbarashev** [comment] 2022-03-21 12:13
Update 3230 was released yesterday. If you installed GanttProject 3.2 beforehand, you need to download a new package from https://www.ganttproject.biz/download/gp30#mac. Simple installation of the update from the Update Channel is not enough, because the fix is in Java Runtime, not in GanttProject.

**Comment by rmb-wdc** [comment] 2022-03-24 19:00
Possibly related, the export feature is failing on my Mac. I get the same result for both the standard download and the above package with the latest Jave 11 runtime.

From the log, here I am trying to export a PDF report, I also get something similar with a PNG:
> Mar 24, 2022 6:52:01 PM net.sourceforge.ganttproject.GPLogger log
INFO: [ProgressMonitorImpl] begin Task: name=Running export
Mar 24, 2022 6:52:01 PM net.sourceforge.ganttproject.GPLogger log
INFO: [ProgressMonitorImpl] begin subTask: name=Generating PDF
Mar 24, 2022 6:52:01 PM net.sourceforge.ganttproject.GPLogger logToLogger
WARNING: Export failure. Failed subtask: Generating PDF
java.lang.RuntimeException: Export failure. Failed subtask: Generating PDF
	at net.sourceforge.ganttproject.export.ExporterBase$2.run(ExporterBase.java:182)
	at org.bardsoftware.impl.eclipsito.JobManagerImpl$GroupWorker.run(JobManagerImpl.java:163)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.itextpdf.text.exceptions.IllegalPdfSyntaxException: Unbalanced save/restore state operators.
	at com.itextpdf.text.pdf.PdfContentByte.sanityCheck(PdfContentByte.java:4193)
	at com.itextpdf.text.pdf.PdfContentByte.toPdf(PdfContentByte.java:318)
	at com.itextpdf.text.pdf.PdfFormXObject.<init>(PdfFormXObject.java:88)
	at com.itextpdf.text.pdf.PdfTemplate.getFormXObject(PdfTemplate.java:262)
	at com.itextpdf.text.pdf.PdfWriter.addXFormsToBody(PdfWriter.java:1353)
	at com.itextpdf.text.pdf.PdfWriter.addSharedObjectsToBody(PdfWriter.java:1364)
	at com.itextpdf.text.pdf.PdfWriter.close(PdfWriter.java:1251)
	at com.itextpdf.text.pdf.PdfDocument.close(PdfDocument.java:901)
	at com.itextpdf.text.Document.close(Document.java:415)
	at org.ganttproject.impex.htmlpdf.itext.ThemeImpl.run(ThemeImpl.java:263)
	at org.ganttproject.impex.htmlpdf.itext.ITextEngine$3.run(ITextEngine.java:217)
	at net.sourceforge.ganttproject.export.ExporterBase$2.run(ExporterBase.java:180)
	... 2 more

**Comment by dbarashev** [comment] 2022-03-24 19:34
@rmb-wdc  This is unrelated. Please create a separate issue and attach the full log, both for PDF and PNG export.

**Comment by rmb-wdc** [comment] 2022-03-28 23:52
> @rmb-wdc This is unrelated. Please create a separate issue and attach the full log, both for PDF and PNG export.

@dbarashev The problem went away with a system reboot. I'll create a separate issue if it recurrs.

**Comment by dbarashev** [comment] 2022-04-01 11:08
Update 3230 reportedly fixed this issue, so I am closing it

https://help.ganttproject.biz/t/ganttproject-crashs-all-the-time-on-my-mac/4368/35

**Closed by dbarashev** 2022-04-01 11:08 UTC
