### ISSUE TITLE
2.8.7 is unusable because the focus is incorrect

### ISSUE THREAD

**Issue by marklinmao** [bardsoftware/ganttproject#1540] opened 2018-05-07 12:26 UTC
Whenever u click any tasks in the left panel, the last item is still marked in blue(which seems that it is still focused), but the actual focus jumped to the new item and start editing....  

This is driving me crazy. This version is totally unusable.

Version 2.8.7, Build 2262, JDK 10.0.1, Win10 1803

**Comment by marklinmao** [comment] 2018-05-07 12:28
![001](https://user-images.githubusercontent.com/4719869/39701806-38a66c18-520b-11e8-9703-c88182a26a92.png)

**Comment by dbarashev** [comment] 2018-05-07 12:29
This seems to be a duplicate of #1528 
The simpliest workaround is to click some other column (not name).

**Closed by dbarashev** 2018-05-07 12:29 UTC
