### ISSUE TITLE
Windows 10 | Surface | 4K Monitor Issues

### ISSUE THREAD

**Issue by AlexanderJB** [bardsoftware/ganttproject#1229] opened 2016-04-01 17:08 UTC
On my MS Surface Pro 4 w/ 2700 x Pixels or on my 4K monitor the UI is barely usable. Arrows and Milestone symbols are barely visible.

![ganntsurfacepro4](https://cloud.githubusercontent.com/assets/18217501/14214346/e46e36c8-f83c-11e5-859e-c8fac958a4f2.png)

I assume more and more user will face the same problems sooner or later when 4K monitors and devices with high resolution become used more and more.

**Comment by ryanthara** [comment] 2016-11-28 05:26
This is a open [bug](https://bugs.openjdk.java.net/browse/JDK-8080153) in the current open jdk versions which is actually not fixed. But the good news is, there is a workaround which can be done to avoid this. 

You have to modify the Java 8 installation on your system to work correctly with a 4K monitor. Therefore you need a program to modify the EXE manifests. In lack of a windows machine I can't test it by myself, but there are a couple of tutorials in the internet. 

Just changed the setting from true to false in the manifests inside of java.exe and javaw.exe, and now the Swing programs scale correctly in Windows 10 high dpi. You can use tools like [Resource Hacker](http://www.restuner.com) or [Resource Tuner](http://www.angusj.com/resourcehacker/) for it.

**Comment by guiweber** [comment] 2017-01-27 04:35
Another high DPI scaling issue I'm seeing is that the text in the task list is cropped because the rows are not scaled with the text
![image](https://cloud.githubusercontent.com/assets/7825368/22360658/e3c616bc-e41f-11e6-8f27-d56a4c284116.png)

This is using the default 250% scaling on a 15 inches 4k monitor under Windows 10.

**Comment by dbarashev** [comment] 2017-02-13 14:00
@guiweber you may want to change base chart font size in the settings to make rows tall enough to fit the font.

**Comment by pmlgeek** [comment] 2017-02-20 18:52
I have exactly the same issue as AlexanderJB.
Could you give me a more understandable version of the solution please, I'm not so advanced in programming!!!
Many thanks

**Comment by dbarashev** [comment] 2017-02-20 19:11
There is no solution for the issue described by Alexander (the size of milestone symbols and arrows). However, if you meant that you want to make fonts larger, you can change them in 
Edit->Settings->Application UI.

**Comment by guiweber** [comment] 2017-02-24 00:13
@dbarashev Thanks, making the base chart font larger does help making the column content more readable. However, even at "very large", the rows are still not tall enough for the letters to fit correctly unless you choose the "smaller" application font size, which makes it too small to read.

**Comment by dbarashev** [comment] 2017-02-25 21:15
@guiweber I guess you're not running the latest GanttProject 2.8.2 and encourage you to upgrade.

**Comment by guiweber** [comment] 2017-02-26 02:01
@dbarashev Yes, I am running 2.8.2. With the base chart font at "very large" and the application font at "large" (which is the right size for my screen), the lower part of the letters "g", "J" and "p" is cut. Also, the "y" in the "Today" button at the top of the chart is cut in the middle.

Also, the Resources Chart doesn't seem to scale with the base chart font size as the lines remain very narrow no matter what font size I select.

But it looks like there is something really weird going on behind the scene: Clicking on "Baseline..." at the top of the chart, makes the lines larger and everything almost fits for the current session (in the Gantt Chart only, the Resource Chart lines remain narrow). When I restart the app, the lines are back to their original smaller size.

**Comment by dbarashev** [comment] 2017-02-27 16:45
@guiweber  

> the lower part of the letters "g", "J" and "p" is cut

You're talking about the task table, aren't you? There was a change in 2.8.2 targeted this very issue, and it should set the row height to the maximum of application font and whatever-chart-wants-it-to-be. Can you tell what font is used (maybe it depends on the font metrics) and share a screenshot how it looks like?

**Comment by guiweber** [comment] 2017-03-02 02:50
@dbarashev The font I'm using is Arial.

Here is what my task list looks like when I open the application. As you can see, the rows are not tall enough for "g", "j" and "p". Also notice that the word "TODAY" at the top of the chart is not fully displayed:
![capturebefore](https://cloud.githubusercontent.com/assets/7825368/23490788/6af219f2-fec8-11e6-81c9-b8160776c586.PNG)

Then, if I click on "Baselines...", the layout immediately changes to this until I close the app:
![captureafter](https://cloud.githubusercontent.com/assets/7825368/23490833/b83672a8-fec8-11e6-97ca-12289dcb9e77.PNG)

However, even after clicking on "Baselines...", the Resources Chart still looks like this:
![captureresource](https://cloud.githubusercontent.com/assets/7825368/23490874/ff216718-fec8-11e6-8695-36fc5d198379.PNG)

**Comment by dbarashev** [comment] 2017-03-02 12:00
I see, thanks. It is not exactly a High DPI issue, it is perfectly reproducible on any display. The issue and workaround are documented in #1345 and in the release notes, and it will surely be fixed in the next update. The issue with resource table is tracked in #1344 and will be fixed in the next update as well.

**Comment by dbarashev** [comment] 2017-03-24 15:59
I hope the particular issue described in this ticket is closed in the new GP 2.8.4. There is DPI option in the settings which scales the majority of UI elements, including milestones and arrows on the chart.

**Closed** 2017-03-30 21:43 UTC
Labels: Fix committed to the repository, HighDPI, Usability
