### ISSUE TITLE
Autosave files not deleted after program close

### ISSUE THREAD

**Issue by EdvinX** [bardsoftware/ganttproject#1295] opened 2016-08-04 11:37 UTC
I searched for this problem and found issue #656 "Please delete autosaves"
Unfortunaltely when I look to my TMP folder there are hundreds of: _ganttproject_autosaveXXXXXXXX.gan files.
Just last one _GanttProject_ps_XXXXX.gan is deleted after program close.

I'm using: GanttProject 2.7.2 Ostrava (build 1954)

**Comment by dbarashev** [comment] 2016-08-04 12:46
This is by design. If you start GanttProject again and close it immediately all autosave files will be deleted.

**Comment by EdvinX** [comment] 2016-08-04 13:02
I've just made a check by opening Ganttproject and closing it right after (without opening any project) and unfortunately about 300 of _ganttproject_autosaveXXXXXXXX.gan files remaines in TMP folder.

**Comment by dbarashev** [comment] 2016-08-04 13:20
What OS are you using?

**Comment by dbarashev** [comment] 2016-08-04 13:26
By the way, try waiting a little bit after opening GanttProject (a few minutes). The matter is that every GanttProject start collects autosave files created by previous launches. it is a background process which starts with a delay and needs to be completed.

**Comment by EdvinX** [comment] 2016-08-04 14:20
I'm using Win7.
I did as you suggested and closed GanttProject after about 40minutes, but all autosave files are still there.

**Closed** 2020-07-09 00:02 UTC
