### ISSUE TITLE
Error no enum constant biz.ganttproject.core.calendar.CalendarEvent.Type.on="5"

### ISSUE THREAD

**Issue by jrking1979** [bardsoftware/ganttproject#1318] opened 2016-11-04 12:25 UTC
![2016-11-04 07_19_16-ganttproject](https://cloud.githubusercontent.com/assets/23259934/20005367/ddc7eb3e-a25f-11e6-9a15-65b074032ab5.png)
[gantt project.docx](https://github.com/bardsoftware/ganttproject/files/571443/gantt.project.docx)

**Comment by dbarashev** [comment] 2016-11-07 01:42
Can you share the project file?

**Comment by dbarashev** [comment] 2017-01-25 14:51
So, most likely the issue is that the project file is broken. Can't say anything more certain without the file, so closing the issue.

**Closed by dbarashev** 2017-01-25 14:51 UTC
